### PR TITLE
Add in health check and the like from springboot

### PR DESCRIPTION
**Pull request by timlevett**
- Add in spring boot actuator for the health check rest endpoint https://spring.io/guides/gs/actuator-service/ available under `/health` or `/health.json`
- Move the base call to `/api/{key}`

### CODE REVIEW

**Comment by apetro** [comment]
_Mind blown._.  Does this expose services that we'd want to IP-restrict or so at the `httpd` layer?

**Comment by paulerickson** [comment]
Changing the path is an incompatible API change, so could you increment the major version?

**Comment by timlevett** [comment]
Agreed @paulerickson, will do. 

@apetro - In the configuration example I've disabled all but `/health` but there are [many options](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html) of things to expose. If we integrate spring security we can use the secure flag to only provide to a specific audience. We could also httpd protect it I suppose.

**Comment by timlevett** [comment]
Note that the actuator services are only active for the sprint-boot app. If you integrate it with an existing application it will not have this functionality.

**Comment by paulerickson** [comment]
:+1:

**Comment by paulerickson** [comment]
You might think about `/proxy/` instead of `/api/`.  If I hypothetically wanted to proxy a service that has multiple endpoints, like `/widgets/api` and `/widgets/heartbeat`, then I would end up with an endpoint `/api/widgets/api`.  In that case, `/proxy/widgets/api` might make it more clear what's going on with the path.

**Comment by vertein** [comment]
I initially though /api would be better and told @timlevett in person.  Given @paulerickson example, I've been convinced that /proxy has more upside.

**Comment by timlevett** [comment]
Yeah, i had brought this up as @vertein iterated. I had the same thought @paulerickson. Will change.

**Pull request merged**
